config/routes.rb
ValidSubdomains = ["sdmcet", "admin"]

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :payment_notifications


  devise_for :users
  #mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match '/', to: 'transcript_applications#index', constraints: { subdomain: 'www' }, via: [:get, :post, :put, :patch, :delete]
  match '/', to: 'transcript_applications#new', constraints: lambda {|request| ValidSubdomains.include?(request.subdomains[0])}, via: [:get, :post, :put, :patch, :delete]

  root to: "transcript_applications#new"

  post '/paypal_ipn_listener', action: :listener, controller: 'paypal_ipn'

  controller :transcript_applications do
    get  'update_transcript_applications'
    post  'update_transcript_applications'
    post  'transcript_applications'
    post  'update_form'
    post  'boolean_form_fields_required'
    post  'new'
    get  'new'
    get  'about_us'
    get  'testimonials'
    get 'states_by_country'

  end

  controller :payments do
    get  'dataForm'
    get  'ccavRequestHandler'
    post  'ccavRequestHandler'
    get  'ccavResponseHandler'
    post  'ccavResponseHandler'
    get 'paypalRequestHandler'
    post 'paypalResponseHandler', :as => :paypal_response_handler
    get 'paymentRequestHandler'
  end

  controller :transactions do
    get  'express'
    get  'new_transaction'
    post  'create'
  end


  get  '/status' => 'orders#application_status', :as => :status
  post '/status' => 'orders#application_status2'
  controller :orders do
    get  'show', :as => :orders_show
    post  'show'
  end

  controller :home do
    get  'account_details'
    get  'temp_individual_application_details'
  end

  get '/transcript_applications/institute_names' => 'transcript_applications#institute_names', :as => :transcript_application_institute_names
  get '/transcript_applications/autofill' => 'transcript_applications#autofill', :as => :transcript_application_autofill
  resources :transcript_applications

  get '/order_items/delete_order' => 'order_items#delete_order', :as => :order_item_delete_order
  resources :order_items
  root to: "products#index"

end

app/controllers/home_controller.rb
#
# Copyright 2017 EduRecords Education Services Pvt Ltd.
#
# Licensed under the Affero General Public License AGPL v3 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.gnu.org/licenses/agpl-3.0.html
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class HomeController < ApplicationController

	def home
	end

	def account_details
		@user = current_user
	end

	def temp_individual_application_details
	end

end

app/helpers/home_helper.rb
#
# Copyright 2017 EduRecords Education Services Pvt Ltd.
#
# Licensed under the Affero General Public License AGPL v3 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.gnu.org/licenses/agpl-3.0.html
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

module HomeHelper
end

app/views/home/account_details.html.erb
<section style="padding: 10%;">
    <div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="page-header">
                    <h1>ACCOUNT DETAILS <small>     LISTING ALL APPLICATIONS ID</small></h1></div>
                </div>
            </div>
        </div>
    </div>
    <div></div>
    <div>
        <div class="container">
            <div class="row" style="background-color: lightblue;">
                <div class="col-md-4" >
                <h3>APPLICATION </h3></div>
                <div class="col-md-4">
                <h3>PAYMENT STATUS</h3></div>
                <div class="col-md-4">
                <h3>FULFILLMENT STATUS</h3></div>
            </div>
        </div>
    </div>
    <div>
        <div class="container" style="font-size: 200%;">
            <div class="row">
                <div class="col-md-4">
                    <%= link_to "7780", temp_individual_application_details_path %>
                </div>
                <div class="col-md-4">Confirmed</div>
                <div class="col-md-4">Pending</div>
            </div>
        </div>
    </div> 
    <div>
        <div class="container"  style="font-size: 200%;">
            <div class="row">
                <div class="col-md-4">
                    <%= link_to "8081", temp_individual_application_details_path %>
                </div>
                <div class="col-md-4">Confirmed</div>
                <div class="col-md-4">Pending</div>
            </div>
        </div>
    </div>
    <div>
        <div class="container" style="padding-top: 3%;">
            <div class="row">
                <div class="col-md-12">
                    <p>FOR MORE DETAILED STATUS CLICK ON APPLICATION NUMBER</p>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/home/temp_individual_application_details.html.erb
<section style="padding: 10%;">
   <div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                <h1>ORDER STATUS</h1></div>
            </div>
        </div>
    </div>
    <div>
        <div class="container">
            <div class="row" style="background-color: lightblue;">
                <div class="col-md-4">
                <h3>APPLICATION NUMBER</h3></div>
                <div class="col-md-3">
                <h3>UNIVERSITY </h3></div>
                <div class="col-md-2">
                <h3>SETS </h3></div>
                <div class="col-md-3">
                <h3>STATUS </h3></div>
            </div>
        </div>
    </div>
    <div>
        <div class="container">
            <div class="row" style="font-size: 200%; padding-top: 2%;">
                <div class="col-md-4">7780</div>
                <div class="col-md-3">Banglore university</div>
                <div class="col-md-2">2</div>
                <div class="col-md-3">Pending</div>
            </div>
        </div>
    </div>
    <div>
        <div class="container">
            <div class="row">
                <div class="col-md-12" style="padding-top: 2%;">
                    <div class="page-header">
                    <h1>BILLING ADDRESS<small>    AND PAYMENT STATUS</small></h1></div>
                </div>
            </div>
        </div>
    </div>
    <div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                <h3>Payment Status :</h3></br>
                <h4>Jay Kulkarni</h4></br>
                <h4>B4/109 Gokulam Apartments, Kanakpura Road </h4></br>
                <h4>Banglore Karnataka </h4></br>
                <h4>India 560011</h4></br>
                <h4>8861114444 </h4></div>
            </div>
        </div>
    </div>
    <div>
        <div class="container">
            <div class="row">
                <div class="col-md-12"></div>
            </div>
        </div>
    </div>
    <div>
        <div class="container">
            <div class="row" style="background-color: lightblue; margin-top: 5%;">
                <div class="col-md-3">
                <h3>ITEM </h3></div>
                <div class="col-md-3">
                <h3>PRICE </h3></div>
                <div class="col-md-3">
                <h3>QUANTITY </h3></div>
                <div class="col-md-3">
                <h3>TOTAL </h3></div>
            </div>
        </div>
    </div>
    <div>
        <div class="container">
            <div class="row" style="font-size: 200%; margin-top: 2%;">
                <div class="col-md-3" style="font-size: 70%; color: grey; margin-top: 1%;"> Custom Service - Rs 11500</div>
                <div class="col-md-3"> Rs 11500</div>
                <div class="col-md-3"> 1 </div>
                <div class="col-md-3"> Rs 11500</div>
            </div>
        </div>
    </div>
    <div>
        <div class="container">
            <div class="row" style="background-color: lightblue; margin-top: 2%;">
                <div class="col-md-3">
                <h3>SUBTOTAL </h3></div>
                <div class="col-md-3"></div>
                <div class="col-md-3"></div>
                <div class="col-md-3">
                <h3> Rs 11500</h3></div>
            </div>
        </div>
    </div>
    <div>
        <div class="container">
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-3"></div>
                <div class="col-md-3"></div>
                <div class="col-md-3"></div>
            </div>
        </div>
    </div>
</section>
</section>