config/routes.rb
ValidSubdomains = ["sdmcet", "admin"]

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :payment_notifications


  devise_for :users
  #mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match '/', to: 'transcript_applications#index', constraints: { subdomain: 'www' }, via: [:get, :post, :put, :patch, :delete]
  match '/', to: 'transcript_applications#new', constraints: lambda {|request| ValidSubdomains.include?(request.subdomains[0])}, via: [:get, :post, :put, :patch, :delete]

  root to: "transcript_applications#new"

  post '/paypal_ipn_listener', action: :listener, controller: 'paypal_ipn'

  controller :transcript_applications do
    get  'update_transcript_applications'
    post  'update_transcript_applications'
    post  'transcript_applications'
    post  'update_form'
    post  'boolean_form_fields_required'
    post  'new'
    get  'new'
    get  'about_us'
    get  'testimonials'
    get 'states_by_country'

  end

  controller :payments do
    get  'dataForm'
    get  'ccavRequestHandler'
    post  'ccavRequestHandler'
    get  'ccavResponseHandler'
    post  'ccavResponseHandler'
    get 'paypalRequestHandler'
    post 'paypalResponseHandler', :as => :paypal_response_handler
    get 'paymentRequestHandler'
  end

  controller :transactions do
    get  'express'
    get  'new_transaction'
    post  'create'
  end


  get  '/status' => 'orders#application_status', :as => :status
  post '/status' => 'orders#application_status2'
  controller :orders do
    get  'show', :as => :orders_show
    post  'show'
  end

  controller :home do
    get  'account_details'
    get  'temp_individual_application_details'
  end

  get '/transcript_applications/institute_names' => 'transcript_applications#institute_names', :as => :transcript_application_institute_names
  get '/transcript_applications/autofill' => 'transcript_applications#autofill', :as => :transcript_application_autofill
  resources :transcript_applications

  get '/order_items/delete_order' => 'order_items#delete_order', :as => :order_item_delete_order
  resources :order_items
  root to: "products#index"

end

app/models/payment_notification.rb
#
# Copyright 2017 EduRecords Education Services Pvt Ltd.
#
# Licensed under the Affero General Public License AGPL v3 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.gnu.org/licenses/agpl-3.0.html
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
class PaymentNotification < ApplicationRecord
	belongs_to :order
	serialize :params
	after_create :mark_order_as_purchased

private
	def mark_order_as_purchased
	  if status == "Completed"
	  	binding.pry
	    order.update_attribute(:purchased_at, Time.now)
	  end
	end
end


# class PaymentNotification < ActiveRecord::Base
#   has_many :kv_entries, :foreign_key => :payment_notification_id, :class_name => 'KvEntry', :dependent => :destroy

#   def sync_instamojo_payments
#     # Some other code
#   end
#   # 5.minutes.from_now will be evaluated when in_the_future is called
#   # handle_asynchronously :sync_instamojo_payments, :run_at => Proc.new { 5.minutes.from_now }

# end

app/controllers/payment_notifications_controller.rb
#
# Copyright 2017 EduRecords Education Services Pvt Ltd.
#
# Licensed under the Affero General Public License AGPL v3 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.gnu.org/licenses/agpl-3.0.html
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class PaymentNotificationsController < ApplicationController
  protect_from_forgery :except => [:create]

  def create
  	PaymentNotification.create!(:params => params, :order_id => params[:invoice], :status => params[:payment_status], :transaction_id => params[:txn_id])
    render :nothing => true
  end


  private
end

app/helpers/payment_notifications_helper.rb
#
# Copyright 2017 EduRecords Education Services Pvt Ltd.
#
# Licensed under the Affero General Public License AGPL v3 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.gnu.org/licenses/agpl-3.0.html
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

module PaymentNotificationsHelper
end

app/views/payment_notifications/_form.html.erb
<%= simple_form_for(@payment_notification) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :params %>
    <%= f.input :order_id %>
    <%= f.input :status %>
    <%= f.input :transaction_id %>
    <%= f.input :create %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/payment_notifications/edit.html.erb
<h1>Editing Payment Notification</h1>

<%= render 'form', payment_notification: @payment_notification %>

<%= link_to 'Show', @payment_notification %> |
<%= link_to 'Back', payment_notifications_path %>

app/views/payment_notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payment Notifications</h1>

<table>
  <thead>
    <tr>
      <th>Params</th>
      <th>Order</th>
      <th>Status</th>
      <th>Transaction</th>
      <th>Create</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payment_notifications.each do |payment_notification| %>
      <tr>
        <td><%= payment_notification.params %></td>
        <td><%= payment_notification.order_id %></td>
        <td><%= payment_notification.status %></td>
        <td><%= payment_notification.transaction_id %></td>
        <td><%= payment_notification.create %></td>
        <td><%= link_to 'Show', payment_notification %></td>
        <td><%= link_to 'Edit', edit_payment_notification_path(payment_notification) %></td>
        <td><%= link_to 'Destroy', payment_notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment Notification', new_payment_notification_path %>

app/views/payment_notifications/new.html.erb
<h1>New Payment Notification</h1>

<%= render 'form', payment_notification: @payment_notification %>

<%= link_to 'Back', payment_notifications_path %>

app/views/payment_notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Params:</strong>
  <%= @payment_notification.params %>
</p>

<p>
  <strong>Order:</strong>
  <%= @payment_notification.order_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @payment_notification.status %>
</p>

<p>
  <strong>Transaction:</strong>
  <%= @payment_notification.transaction_id %>
</p>

<p>
  <strong>Create:</strong>
  <%= @payment_notification.create %>
</p>

<%= link_to 'Edit', edit_payment_notification_path(@payment_notification) %> |
<%= link_to 'Back', payment_notifications_path %>