config/routes.rb
ValidSubdomains = ["sdmcet", "admin"]

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :payment_notifications


  devise_for :users
  #mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match '/', to: 'transcript_applications#index', constraints: { subdomain: 'www' }, via: [:get, :post, :put, :patch, :delete]
  match '/', to: 'transcript_applications#new', constraints: lambda {|request| ValidSubdomains.include?(request.subdomains[0])}, via: [:get, :post, :put, :patch, :delete]

  root to: "transcript_applications#new"

  post '/paypal_ipn_listener', action: :listener, controller: 'paypal_ipn'

  controller :transcript_applications do
    get  'update_transcript_applications'
    post  'update_transcript_applications'
    post  'transcript_applications'
    post  'update_form'
    post  'boolean_form_fields_required'
    post  'new'
    get  'new'
    get  'about_us'
    get  'testimonials'
    get 'states_by_country'

  end

  controller :payments do
    get  'dataForm'
    get  'ccavRequestHandler'
    post  'ccavRequestHandler'
    get  'ccavResponseHandler'
    post  'ccavResponseHandler'
    get 'paypalRequestHandler'
    post 'paypalResponseHandler', :as => :paypal_response_handler
    get 'paymentRequestHandler'
  end

  controller :transactions do
    get  'express'
    get  'new_transaction'
    post  'create'
  end


  get  '/status' => 'orders#application_status', :as => :status
  post '/status' => 'orders#application_status2'
  controller :orders do
    get  'show', :as => :orders_show
    post  'show'
  end

  controller :home do
    get  'account_details'
    get  'temp_individual_application_details'
  end

  get '/transcript_applications/institute_names' => 'transcript_applications#institute_names', :as => :transcript_application_institute_names
  get '/transcript_applications/autofill' => 'transcript_applications#autofill', :as => :transcript_application_autofill
  resources :transcript_applications

  get '/order_items/delete_order' => 'order_items#delete_order', :as => :order_item_delete_order
  resources :order_items
  root to: "products#index"

end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} application packet in Cart ( #{number_to_currency current_order.subtotal} )", show_path, class: "btn btn-link" %>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <p><strong>This form contains <%= pluralize(object.errors.count, 'error') %>.</strong></p>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<section class="ctrans-section ctrans-section--relative ctrans-section--fixed-size" id="contacts2-90" style="background-color: rgb(60, 60, 60);">
   <div class="ctrans-section__container container">
      <div class="ctrans-contacts ctrans-contacts--wysiwyg row">
         <div class="col-sm-6">
            <figure class="ctrans-figure ctrans-figure--wysiwyg ctrans-figure--full-width ctrans-figure--no-bg">
               <div class="ctrans-figure__map ctrans-figure__map--short ctrans-google-map">
                  <p class="ctrans-google-map__marker" data-coordinates="12.9329463,77.58386919999998"></p>
               </div>
            </figure>
         </div>
         <div class="col-sm-6">
            <div class="row">
               <div class="col-sm-5 col-sm-offset-1">
                  <p class="ctrans-contacts__text"><strong>ADDRESS</strong><br>
                     ClearTranscripts<br>
                     #16, 10th Main<br>
                     Jayanagar 3rd Block<br>
                     Bengaluru 560011, KA, India.<br><br>
                     <strong>CONTACTS</strong><br>
                     Email: customerservice@cleartranscripts.com<br>
                     Phone: INDIA +918030752740<br>
                     Phone: Intl: +19174844990
                  </p>
               </div>
               <div class="col-sm-6">
                  <p class="ctrans-contacts__text"><strong>LINKS</strong></p>
                  <ul class="ctrans-contacts__list">
                     <li><a href="" class="text-gray">HOME</a><a class="ctrans-contacts__link text-gray" href=""></a></li>
                     <li><a href="" class="text-gray">GUIDELINES</a><a class="ctrans-contacts__link text-gray" href=""></a></li>
                     <li><a href="" class="text-gray">VIDEO</a></li>
                     <li><a href="" class="text-gray">BLOG</a></li>
                     <li><br></li>
                  </ul>
               </div>
            </div>
         </div>
      </div>
   </div>
</section>
<section>
<footer class="ctrans-section ctrans-section--relative ctrans-section--fixed-size" id="footer1-91" style="background-color: #1673e6;">
   <div class="ctrans-section__container container">
      <div class="ctrans-footer ctrans-footer--wysiwyg row">
         <div class="col-sm-12">
            <p class="ctrans-footer__copyright"></p>
            <p style="color: white;">Copyright © 2016 EduRecords Education Services Pvt Ltd  <a href="license.txt" style="color: white;">License</a></p>
            <p></p>
         </div>
      </div>
   </div>
</footer>
</section>

app/views/layouts/_header.html.erb
<section class="ctrans-navbar ctrans-navbar--freeze ctrans-navbar--absolute ctrans-navbar--transparent ctrans-navbar--sticky ctrans-navbar--auto-collapse" id="menu-74">
   <div class="ctrans-navbar__section ctrans-section" style="background-color: #1673e6;">
   <div class="ctrans-section__container container">
      <div class="ctrans-navbar__container">
         <div class="ctrans-navbar__column ctrans-navbar__column--s ctrans-navbar__brand">
            <span class="ctrans-navbar__brand-link ctrans-brand ctrans-brand--inline">
            <span class="ctrans-brand__logo"><a href="/">
            <img class="ctrans-navbar__brand-img ctrans-brand__img" src="assets/logo.png" alt="Cleartranscripts"></a></span>
            <span class="ctrans-brand__name">
              <div class="row">
                <div class="col-md-6 col-md-offset-3">
                  <%= link_to "Application Packet: "+((@order.nil? or @order.order_items.nil?) ? 0 : @order.order_items.size).to_s, show_path, :id => 'application_packet', :class => "float:left;text-right text-nowrap", :style=>"font-size:14px;color:white;" %>
                </div>
              </div>
            </span>
            </span>
         </div>
         <div class="ctrans-navbar__hamburger ctrans-hamburger text-white" ><span class="ctrans-hamburger__line"></span></div>
         <div class="ctrans-navbar__column ctrans-navbar__menu">
            <nav class="ctrans-navbar__menu-box ctrans-navbar__menu-box--inline-right">
               <div class="ctrans-navbar__column">
                  <ul class="ctrans-navbar__items ctrans-navbar__items--right  ctrans-buttons ctrans-buttons--freeze ctrans-buttons--right btn-decorator ctrans-buttons--active">
                     <li class="ctrans-navbar__item">
                        <a class="ctrans-buttons__link btn text-white" href="/" style="color: white;">HOME</a>
                     </li>
                    <li class="ctrans-navbar__item">
                      <a class="ctrans-buttons__link btn text-white" href="/status" style="color: white;">APPLICATION STATUS</a>
                    </li>
                     <li class="ctrans-navbar__item">
                       <a class="ctrans-buttons__link btn text-white" href="<%=testimonials_path%>" style="color: white;">TESTIMONIALS</a>
                     </li>
                  </ul>
               </div>
               <div class="ctrans-navbar__column">
                    <ul class="ctrans-navbar__items ctrans-navbar__items--right ctrans-buttons ctrans-buttons--freeze ctrans-buttons--right btn-inverse ctrans-buttons--active">
                        <li class="ctrans-navbar__item">
                            <%= render 'devise/menu/login_items' %>
                        </li>
                        <li class="ctrans-navbar__item">
                            <%= render 'devise/menu/registration_items' %>
                        </li>
                    </ul>
                </div>
            </nav>
         </div>
      </div>
   </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="Cleartranscripts v2.6.1, cleartranscripts.com">
    <link rel="shortcut icon" href="assets/images/discover-mobile-350x350-16.png" type="image/x-icon">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:700,400&amp;subset=cyrillic,latin,greek,vietnamese">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Slackey" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Fredoka+One" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Wallpoet" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Hanalei+Fill" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Signika" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Fredoka+One" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Fredoka+One">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Slackey">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <title><%= content_for?(:title) ? yield(:title) : "ClearTranscripts" %></title>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  </head>
  <body>
    <% unless request.path =~ /users\/*/ %>
        <%= render "layouts/header" %>
    <% end %>
    <%= yield %>
    <% unless request.path =~ /users\/*/ %>
        <%= render "layouts/footer" %>
    <% end %>
   <!-- <script src="https://maps.googleapis.com/maps/api/js"></script>-->
  </body>
</html> 